### PR TITLE
Allow custom CA Bundle

### PR DESCRIPTION
**Pull request by iwoloschin**
Quick patch to allow a custom CA Bundle to be specified, just like requests.

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Great, yup.

Could you point me to the corresponding point in requests source code? Does requests have test cases for this area of functionality? We’ve not got any around ssl verification yet, and might be fiddly, but would be super helpful if there’s a reference we can work from.

**Comment by iwoloschin** [comment]
Here's a link to the requests code:

https://github.com/kennethreitz/requests/blob/master/requests/adapters.py#L219

You can see I just copied the IOError if the custom CA Bundle is not found as well.  I'm mildly conflicted on that, and kind of think it should be a slightly different error message (but the same IOError) for requests-async to help future users go to the right project.  Thoughts?

As far as test cases for SSL...I have no idea!  I assume yes, but I'm not familiar with the requests test cases, so it might take a bit to go figure out.

**Comment by lovelydinosaur** [comment]
>  I'm mildly conflicted on that, and kind of think it should be a slightly different error message

No I think it's fine - makes no difference between `requests` and `requests-async`, and besides, the info's there in a traceback if anyone cares to dig deeped.

**Comment by lovelydinosaur** [comment]
Let's roll with this for now then - great work!

**Comment by iwoloschin** [comment]
Awesome, thanks!

**Pull request merged**
