### PR TITLE
Connection pool feature - Part 1

### PR DESCRIPTION
**Pull request by sebrestin**
I created this initial PR with a simple PoolManager for both HTTP and HTTPS which always returns a new connection.

I tried to mimic all the API used in requests and urllib3.

After I get feedback, if this implementation is on the right track, I would like to add tests as well.

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Okay - some really good work here, tho I think the change footprint on this is probably going to be too large. Not sure I can adequately review it in it's current form.
Ideally we'd do something more incrementally.

**Comment by sebrestin** [comment]
OK. How do you want to go about it? As discussed, this PR is just a pool manager which just returns a new connection. I was thinking that you could create a branch on your side. I will push each PR to the branch and when it is done-done, just merge that branch into master.

**Comment by lovelydinosaur** [comment]
On reviewing #7, #8, and #10 - in order to fulfil all of those I think we'll end up wanting a complete port of urlib3 to asyncio. I guess we need to think about the best approach - I suppose ultlimately we'll probably want a proper `urllib3-async` package.

**Comment by lovelydinosaur** [comment]
> I think we'll end up wanting a complete port of urlib3 to asyncio

On working into this further I've revised my opinion 😝

I think it'll actually liekly be less effort to gradually move away from relying on urllib3 here.

**Comment by lovelydinosaur** [comment]
So, this is the (stubbed out) ConnectionPool... https://github.com/encode/requests-async/blob/master/requests_async/connections.py

The adapter class now doesn't get connections itself, but calls into that class instead.

**Pull request closed without merging**
