### PR TITLE
Revisit connection pooling

### PR DESCRIPTION
**Pull request by lovelydinosaur**
In progress

### CODE REVIEW

**Comment by sebrestin** [comment]
I have reviewed the work you did last week. I don't understand why this approach is better than #28 . My understanding was that this should be an async version of requests. I wanted to propose an urllib3 async implementation, but I realized that with time we could naturally branch it out from this repo. So my question is what made you change your mind and not follow the urllib3 API as discussed in #10 ?

**Comment by lovelydinosaur** [comment]
I think where we'll actually go with this is probably plugging into https://github.com/encode/httpcore from the adapter class. (Instead of plugging into urllib3)

**Comment by sebrestin** [comment]
So basically httpcore is somewhat similar to what they want to do here https://github.com/core (https://www.kennethreitz.org/essays/the-future-of-python-http)?

**Comment by lovelydinosaur** [comment]
Yes.

**Comment by lovelydinosaur** [comment]
Oh blimey, they've even called it the same thing 🤣

**Comment by lovelydinosaur** [comment]
Some *minor* differences in the level of abstraction - the `httpcore` lib I've got going here is just a *little* lower-level - mapping more directly just to the actual network representation. E.g. headers are just lists of byte-pairs, and it's up to higher level libs to provide model wrappers on top of it.

**Comment by lovelydinosaur** [comment]
Also, where they've proposed `httpcore` as the common interface between components, I'd suggest working at the ASGI level instead.

Eg. "Today, making real HTTP Requests to an in-process WSGI app with a real HTTP client is not simple. Can you imagine writing real OAuth tests for your application with the same HTTP consumer your clients will use?"

Well, yes `requests-async`'s `ASGISession` essentially gives you the ability to do that.

**Comment by lovelydinosaur** [comment]
Superseeded by #37

**Pull request closed without merging**
